# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-01-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_documento', models.CharField(max_length=20, unique=True)),
                ('numero_de_libreta_militar', models.CharField(blank=True, max_length=20, null=True)),
                ('primer_apellido', models.CharField(max_length=140)),
                ('segundo_apellido', models.CharField(blank=True, max_length=140)),
                ('primer_nombre', models.CharField(max_length=140)),
                ('segundo_nombre', models.CharField(blank=True, max_length=140)),
                ('fecha_de_nacimiento', models.DateField(blank=True, help_text='(aaaa-MM-dd)', null=True)),
            ],
            options={
                'ordering': ['primer_apellido', 'segundo_apellido'],
            },
        ),
    ]
